kind: Deployment
apiVersion: apps/v1
metadata:
    name: jbird
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jbird
  template:
      metadata:
        labels:
          app: jbird
      spec:
        containers:
          - name: jbird
            image: jbird1996/docker-pipeline
            imagePullPolicy: Always
            ports:
            - containerPort: 80