kind: Service
apiVersion: v1
metadata:
  name: Jbird
  labels:
    app: Jbird
spec:
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31200
  selector:
    app: Jbird
  type: LoadBalancer