kind: Service
apiVersion: v1
metadata:
  name: jbird
  labels:
    app: jbird
spec:
  ports:
    - protocol: 'TCP'
      port: 8080
      targetPort: 80
      nodePort: 31200
  selector:
    app: jbird
  type: LoadBalancer