apiVersion: v1
kind: Service
metadata:
  name: jbird
  labels:
    app: jbird
spec:
  ports:
  - protocol: 'TCP'
    port: 80
    targetPort: 80
    nodePort: 31210
  selector:
    app: jbird
  type: LoadBalancer