kind: Service
apiVersion: v1
metadata:
  name: jbird
  labels:
    app: jbird
spec:
  ports:
    - port: 8083
      targetPort: 80
      nodePort: 31200
  selector:
    app: jbird
  type: LoadBalancer